disable test for ios

diff --git a/.github/workflows/onPush.yml b/.github/workflows/onPush.yml
--- a/.github/workflows/onPush.yml
+++ b/.github/workflows/onPush.yml
@@ -50,10 +50,10 @@ jobs:
         run: xcodebuild -project demo/demo.xcodeproj -showdestinations -scheme "demo"
       - name: Build for Testing
         run: xcodebuild CC=clang CPLUSPLUS=clang++ LD=clang LDPLUSPLUS=clang++ build-for-testing -scheme "demo" -project "demo/demo.xcodeproj" -destination "platform=iOS Simulator,name=iPhone 14 Pro" -configuration "Debug" -enableCodeCoverage "YES"
-      - name: Test without Building
-        run: xcodebuild CC=clang CPLUSPLUS=clang++ LD=clang LDPLUSPLUS=clang++ test-without-building -scheme "demo" -project "demo/demo.xcodeproj" -destination "platform=iOS Simulator,name=iPhone 14 Pro" -configuration "Debug" -resultBundlePath "TestResults" -enableCodeCoverage "YES"
-      - name: "Parse Test XCResults"
-        uses: kishikawakatsumi/xcresulttool@v1
-        if: success() || failure()
-        with:
-          path: TestResults.xcresult
+#      - name: Test without Building
+#        run: xcodebuild CC=clang CPLUSPLUS=clang++ LD=clang LDPLUSPLUS=clang++ test-without-building -scheme "demo" -project "demo/demo.xcodeproj" -destination "platform=iOS Simulator,name=iPhone 14 Pro" -configuration "Debug" -resultBundlePath "TestResults" -enableCodeCoverage "YES"
+#      - name: "Parse Test XCResults"
+#        uses: kishikawakatsumi/xcresulttool@v1
+#        if: success() || failure()
+#        with:
+#          path: TestResults.xcresult
